-- ============================================================
-- ERP AviZee — Marcador de migração (seed removido)
--
-- Este arquivo existia como seed destrutivo dentro do fluxo
-- de migrations, o que é uma prática insegura.
--
-- A lógica de reset e carga de dados de exemplo foi movida para:
--   supabase/seeds/reset.sql  — limpeza controlada de dados
--   supabase/seeds/seed.sql   — inserção de dados de exemplo
--
-- Para recriar uma base de desenvolvimento, use:
--   npm run dev:reset          (requer --confirm explícito)
--   npm run seed:reset         (somente limpeza)
--   npm run seed:data          (somente inserção)
--
-- NÃO execute esses scripts em produção.
-- ============================================================

-- (migration neutra — nenhuma alteração de schema ou dados)
