// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

export const supabaseConfigError = !SUPABASE_URL
  ? "Configuração ausente: defina VITE_SUPABASE_URL no ambiente de publicação."
  : !SUPABASE_PUBLISHABLE_KEY
    ? "Configuração ausente: defina VITE_SUPABASE_PUBLISHABLE_KEY (ou VITE_SUPABASE_ANON_KEY) no ambiente de publicação."
    : null;

export const isSupabaseConfigured = !supabaseConfigError;

const FALLBACK_URL = "https://vhwhxvsfkossbrfbeawa.supabase.co";
const FALLBACK_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwbGFjZWhvbGRlciIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDAwMDAwMDAsImV4cCI6MjcwMDAwMDAwMH0.placeholder-signature";

if (supabaseConfigError) {
  console.error("[Supabase] " + supabaseConfigError);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL || FALLBACK_URL, SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
